print("Available commands:\n")

print("echo <text>")
print("exit")
print('clear')
print('help')
print("python")
print("neofetch")
print("shutdown")
print("app <app>")
print("expr <expression>")
print('ver\n')
